pp_d8cards.settings:
  type: config_object
  label: 'PP D8 Cards config'
  mapping:
    message:
      type: text
      label: 'Message PP D8 Cards'
    is_happy:
      type: boolean
      label: 'Is Happy ?'
    colors:
      type: sequence
      label: 'Colors'
      sequence:
        type: string
        label: 'Color'
